### ISSUE TITLE
Error in install/run

### ISSUE THREAD

**Issue by PoetaGA** [systemsplanet/java-vipaccess#1]
Error in install/run

Error in install

"] java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 400 Bad Request"
[Fatal Error] :1:1: Premature end of file.
Exception in thread "main" org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
at com.systemsplanet.vipaccess.http.VipToken.parse(VipToken.java:88)
at com.systemsplanet.vipaccess.VipAccessMain.main(VipAccessMain.java:24)"

**Comment by systemsplanet-zz** [comment]
Symantec has disabled the rest API to validate a token. You can comment out
the tests and it should still work

mike lawrence    404 841 7800

On May 2, 2017 8:30 AM, "PoetaGA" <notifications@github.com> wrote:

Error in install/run

Error in install

"] java.io.IOException: Unable to tunnel through proxy. Proxy returns
"HTTP/1.1 400 Bad Request"
[Fatal Error] :1:1: Premature end of file.
Exception in thread "main" org.xml.sax.SAXParseException; lineNumber: 1;
columnNumber: 1; Premature end of file.
at com.sun.org.apache.xerces.internal.parsers.DOMParser.
parse(DOMParser.java:257)
at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(
DocumentBuilderImpl.java:339)
at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
at com.systemsplanet.vipaccess.http.VipToken.parse(VipToken.java:88)
at com.systemsplanet.vipaccess.VipAccessMain.main(VipAccessMain.java:24)"

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/systemsplanet/java-vipaccess/issues/1>, or mute the
thread

**Comment by systemsplanet-zz** [comment]
Please post the debug output from line 22 which dumps the XML

https://github.com/systemsplanet/java-vipaccess/blob/master/app/vipaccess/src/main/java/com/systemsplanet/vipaccess/VipAccessMain.java


mike lawrence    404 841 7800

**Comment by systemsplanet-zz** [comment]
please pull  the latest and execute run.cmd.
I increased the logging to troubleshoot your issue.

I just created a new OTP key and registered it with etrade, and was able to login, so it is working for me using the Yubikey to store the OTP.
